### ISSUE TITLE
organize loose files in manuscript-object repo

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/manuscript-object#24]
There are many loose files in this repo, @gschare please use your discretion to organize the files into related projects, etc.

**Comment by njr2128** [comment]
@gschare, there seem to also be some loose files in https://github.com/cu-mkp/m-k-manuscript-data/tree/master that should go under manuscript-object:
![image](https://user-images.githubusercontent.com/14779727/90527053-1f261480-e13f-11ea-919a-96023228e53f.png)

**Comment by gschare** [comment]
@njr2128 Which ones specifically do not appear to belong? I defer to your experience with the repo. I'm assuming the bash scripts, but I just want to make sure.

**Comment by njr2128** [comment]
@gschare, I think the bash scripts as well as the mk-fq-cnts files - they were ones generated by Matthew as part of thesaurus work, so I think there should be a home for them somewhere in object, right? If not, maybe we should make one. 
As for the pip files and update.py/check_update.py - would it make sense to just put these all in a directory together in manuscript-data?
@tcatapano, perhaps you have some thoughts?
