### ISSUE TITLE
update.py: allow user-provided path to /m-k-manuscript-data

### ISSUE THREAD

**Issue by gschare** [cu-mkp/manuscript-object#38]
- Currently update.py assumes that m-k-manuscript-data is on the same level as its own parent directory, manuscript-object.
- We should add an optional argument to specify the user's own local path to m-k-manuscript-data.
- We should also implement some naive sanity checks to make sure the given path actually contains the original ms-xml files, and issue an error if not.
- Also ask user to confirm (y/n) whether the provided path makes sense. Allow this check to be silenced in case we need to automate.

**Comment by gschare** [comment]
How it is implemented:
- positional "path" argument allows user to specify m-k-manuscript-data path
- the '-b' or '--bypass' flag bypasses the user confirmation of the path
- will raise AssertionError if path does not exist or if ms-xml is not found inside of it
- defaults to ../m-k-manuscript-data, relative to the path of update.py

also:
- helper functions like generate_complete_manuscript() now require positional manuscript_data_path argument

**Comment by njr2128** [comment]
confirming: 
![image](https://user-images.githubusercontent.com/14779727/93124339-787a5880-f697-11ea-8d33-14023a66c056.png)
