### ISSUE TITLE
new "base swarmplot" with just entry distribution

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/manuscript-object#45]
https://github.com/ronikaufman/manuscript-object/tree/context/manuscript_visualizations/swarmplots
has Roni's "swarmplots" which show the ms entries across the ms, highlighting dif tag occurrences across the folios. 

However, there is no "base" plot: one which JUST has the entry distribution across the categories, with no indication of any specific tags (ie showing just the grey bars).

The sourcecode is here: https://github.com/ronikaufman/manuscript-object/blob/context/context_viz.py

**Comment by gschare** [comment]
For future reference:
the file which generates the swarmplots and other manuscript visualizations is actually [manuscript_visualizations.py](https://github.com/ronikaufman/manuscript-object/blob/context/manuscript_visualizations.py).

**Comment by gschare** [comment]
Added blank swarmplot to the sandbox folder. See it [here](https://github.com/cu-mkp/manuscript-object/blob/master/sandbox/blank_swarmplot.png).
If we need more visualizations like this, it will be easier going forward to update Roni's code than to keep using his. I don't _think_ there will be any inaccuracies for this plot but his version of manuscript-object is far behind the current release, which means it's using older methods of analyzing the text which we know to have many bugs.
