### ISSUE TITLE
add <fr> to entry-metadata

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/manuscript-object#63]
`<fr>` is currently not pulled out in entry-metadata because it is ONLY used in tl.

We had not pulled this tag in entry-metadata (and any other derivative file it may be relevant to) because it is only in tl.

However, we do want this tag now pulled (just as we pull all the other languages). 

NOTE for @ps2270 and @njr2128, we do not want `<fr>` pulled for List of Entries by Nick, so before we make this change, we need to confirm that adding this tag will not create a lot of work to get around it or generate an error.

**Comment by gschare** [comment]
As far as I know, this should be a one-line change to `utils.py`, so let me know what you decide.

**Comment by njr2128** [comment]
UPDATE:
We want to pull this now BUT not have it be part of List of Entries
> This is fine bc the list of filters is a hard-coded list

Need to confirm that adding this tag will not create a lot of work to get around it or generate an error. - ie if we add <fr>, will it break anything
>Probably not.
TO DO: Go forward with adding <fr> by @gschare , and once entry-metadata has <fr>, do a build to staging and confirm it does break anything
