### ISSUE TITLE
draft v2.0.1 release of repo

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/manuscript-object#68]
@gschare, as we did for v2.0.0, let's tag a release for the current state of the repo. Please add notes from relevant pull requests and issues (and if you feel the changes or bug fixes are significant enough, perhaps tag as v2.1.0 - whatever you think is best!)

This will correspond with m-k-manuscript-data release v1.2.1

**Comment by njr2128** [comment]
DECISION: to do next week? Using Greg's discretion

**Comment by gschare** [comment]
Using current state of master branch of Feb 8 for release. See release_v2.0.1 branch.
Note that this state does not include testing as described in #51.
