### ISSUE TITLE
create tagged release from Dana's fork

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/manuscript-object#82]
https://github.com/danachaillard/manuscript-object

Follow the procedure undertaken to produce https://github.com/cu-mkp/manuscript-object/tree/v1.0-ronikaufman (to be documented here by @gschare)

**Comment by gschare** [comment]
Steps for pushing a fork to a new branch:
1. Create a new branch in the target repo
2. Checkout that branch
3. Locate in the fork's history the last commit before it was forked and note the commit hash
4. Do `git reset --hard [commit-hash]`
5. Do `git clean -df`
6. Do `git push -f origin [branch-name]`
7. Pull request in the fork from the branch of the fork that you want into the newly created and pushed branch of the target repo.
8. Merge the pull request

**Comment by njr2128** [comment]
Done! https://github.com/cu-mkp/manuscript-object/tree/v1.0-danachaillard
