### ISSUE TITLE
Generate figure metadata for SU21 student project

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/manuscript-object#87]
Info for each figure:

- associated entry id 
- associated entry header (TL only)
- In a margin? Position?
- entry categories of the entry associated with figure
- Semantic tags of associated figure for TL only (like in https://github.com/cu-mkp/m-k-manuscript-data/blob/master/metadata/entry_metadata.csv)
- Size of image

**Comment by gschare** [comment]
Code is available in [projects/sophie-macomber-figures](https://github.com/cu-mkp/manuscript-object/tree/master/projects/sophie-macomber-figures).
