### ISSUE TITLE
update.py is generating funky allFolios

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/manuscript-object#92]
The entries are out of order. See, eg, https://github.com/cu-mkp/m-k-manuscript-data/blob/master/allFolios/xml/tl/all_tl.xml which begins with 24r

**Comment by tcatapano** [comment]
I think the relevant code block is:
https://github.com/cu-mkp/manuscript-object/blob/a4bce628afc62213d785b340b40b9cb7814217d0/manuscript.py#L298-L316

can these items be sorted by id prior to outputting?

Also, I think this actually outputting all entries not all folios which is fine but should be named "all_entries.xml" and still would be good to have an "all_folios.xml"

**Comment by tcatapano** [comment]
I think this is actually outputting all *entries* not all *folios*, which is fine but should be named "all_entries.xml" and still would be good to have an "all_folios.xml"

**Comment by gschare** [comment]
Added a hotfix, see #93.

> Fixes #92. I added a hotfix by just sorting the entries by folio as they come, in `generate_all_folios`.
> 
> There are two reasons why this happened (as far as I can tell; I didn't look very closely):
> 
> 1. there is no particular order in which Python reads the files from the source directory, and we never sort these after they come in. I fixed this by sorting the list of entries after they are read.
> 2. the folios names are not padded. This means that `111v` comes before `12v`. I fixed this by leftpadding the folio with 0's for sorting purposes, **temporarily**. So `012v` comes before `111v`.
> 
> I held off from padding the stored folio name attribute in the `Entry` object because I'm not sure if there is a reason for this. It might be important that they are unpadded. I am pretty sure that the `folio` attribute of an `Entry` object doesn't affect the XML or TXT output, but it probably is used elsewhere, maybe in the CSV. Perhaps we wanted them unpadded in the CSV. @njr2128 do you know?

I don't think it's generating entries. It is hard to tell the difference because it still keeps the entry div tags in the all_folios.xml output. Would you like me to remove these?
